/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VersionHistoryRouteImport } from './routes/version-history'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScreenplaysRouteImport } from './routes/screenplays'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PoetryRouteImport } from './routes/poetry'
import { Route as LyricsRouteImport } from './routes/lyrics'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const VersionHistoryRoute = VersionHistoryRouteImport.update({
  id: '/version-history',
  path: '/version-history',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenplaysRoute = ScreenplaysRouteImport.update({
  id: '/screenplays',
  path: '/screenplays',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PoetryRoute = PoetryRouteImport.update({
  id: '/poetry',
  path: '/poetry',
  getParentRoute: () => rootRouteImport,
} as any)
const LyricsRoute = LyricsRouteImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/editor': typeof EditorRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/lyrics': typeof LyricsRoute
  '/poetry': typeof PoetryRoute
  '/profile': typeof ProfileRoute
  '/screenplays': typeof ScreenplaysRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/stories': typeof StoriesRoute
  '/version-history': typeof VersionHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/editor': typeof EditorRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/lyrics': typeof LyricsRoute
  '/poetry': typeof PoetryRoute
  '/profile': typeof ProfileRoute
  '/screenplays': typeof ScreenplaysRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/stories': typeof StoriesRoute
  '/version-history': typeof VersionHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/drafts': typeof DraftsRoute
  '/editor': typeof EditorRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/lyrics': typeof LyricsRoute
  '/poetry': typeof PoetryRoute
  '/profile': typeof ProfileRoute
  '/screenplays': typeof ScreenplaysRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/stories': typeof StoriesRoute
  '/version-history': typeof VersionHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bookmarks'
    | '/dashboard'
    | '/drafts'
    | '/editor'
    | '/explore'
    | '/library'
    | '/lyrics'
    | '/poetry'
    | '/profile'
    | '/screenplays'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/stories'
    | '/version-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bookmarks'
    | '/dashboard'
    | '/drafts'
    | '/editor'
    | '/explore'
    | '/library'
    | '/lyrics'
    | '/poetry'
    | '/profile'
    | '/screenplays'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/stories'
    | '/version-history'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bookmarks'
    | '/dashboard'
    | '/drafts'
    | '/editor'
    | '/explore'
    | '/library'
    | '/lyrics'
    | '/poetry'
    | '/profile'
    | '/screenplays'
    | '/settings'
    | '/sign-in'
    | '/sign-up'
    | '/stories'
    | '/version-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookmarksRoute: typeof BookmarksRoute
  DashboardRoute: typeof DashboardRoute
  DraftsRoute: typeof DraftsRoute
  EditorRoute: typeof EditorRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  LyricsRoute: typeof LyricsRoute
  PoetryRoute: typeof PoetryRoute
  ProfileRoute: typeof ProfileRoute
  ScreenplaysRoute: typeof ScreenplaysRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  StoriesRoute: typeof StoriesRoute
  VersionHistoryRoute: typeof VersionHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/version-history': {
      id: '/version-history'
      path: '/version-history'
      fullPath: '/version-history'
      preLoaderRoute: typeof VersionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screenplays': {
      id: '/screenplays'
      path: '/screenplays'
      fullPath: '/screenplays'
      preLoaderRoute: typeof ScreenplaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poetry': {
      id: '/poetry'
      path: '/poetry'
      fullPath: '/poetry'
      preLoaderRoute: typeof PoetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lyrics': {
      id: '/lyrics'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookmarksRoute: BookmarksRoute,
  DashboardRoute: DashboardRoute,
  DraftsRoute: DraftsRoute,
  EditorRoute: EditorRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  LyricsRoute: LyricsRoute,
  PoetryRoute: PoetryRoute,
  ProfileRoute: ProfileRoute,
  ScreenplaysRoute: ScreenplaysRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  StoriesRoute: StoriesRoute,
  VersionHistoryRoute: VersionHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
